### ISSUE TITLE
ImageNet?

### ISSUE THREAD

**Issue by hendrycks** [KaiHoo/RotationOut#1]
@KaiHoo The paper contains an ImageNet experiment. Is there code for this or at least model weights? Thank you.

**Comment by KaiHoo** [comment]
Thank you for your interest (But we did not mention this Github repository in the open review website nor mention the paper here. Hope that it does not violate the policy of ICLR). 

The answer is yes if our paper is accepted. But unfortunately, it seems that we should focus on the next conference. We will release full codes for ImageNet, COCO, WSJ and maybe Penn Treebank/WikiText-2 once we complete the new version and let you know once we finish.

**Comment by hendrycks** [comment]
OK, my main interest is in the weights to see if the model is more robust to common corruptions. Sometimes gains in clean dataset accuracy are 1%, but gains in robustness may be significant.
